// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8lV6QFWAyZd1j1gLfsl9Y5oL0tmf5ps',
    appId: '1:564448752554:web:04d2a1edb8ada89b6771d3',
    messagingSenderId: '564448752554',
    projectId: 'myfirstdata-2717f',
    authDomain: 'myfirstdata-2717f.firebaseapp.com',
    storageBucket: 'myfirstdata-2717f.appspot.com',
    measurementId: 'G-LK517BFN57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwGIwGa_0UwSKY4mOzUrpMadUwhcupCz4',
    appId: '1:564448752554:android:948191776cfed57d6771d3',
    messagingSenderId: '564448752554',
    projectId: 'myfirstdata-2717f',
    storageBucket: 'myfirstdata-2717f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm4NWr_alhkFUNYl1AhdVMJxFdivF5-W8',
    appId: '1:564448752554:ios:1014ed5944a9cabf6771d3',
    messagingSenderId: '564448752554',
    projectId: 'myfirstdata-2717f',
    storageBucket: 'myfirstdata-2717f.appspot.com',
    iosClientId: '564448752554-3nqqtuchanorjr12e2r1n00li0lfctb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm4NWr_alhkFUNYl1AhdVMJxFdivF5-W8',
    appId: '1:564448752554:ios:1014ed5944a9cabf6771d3',
    messagingSenderId: '564448752554',
    projectId: 'myfirstdata-2717f',
    storageBucket: 'myfirstdata-2717f.appspot.com',
    iosClientId: '564448752554-3nqqtuchanorjr12e2r1n00li0lfctb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstdata',
  );
}
